apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-hello-world-deployment
spec:
  selector:
    matchLabels:
      app: docker-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-hello-world
    spec:
      containers:
        - name: static-web-app
          image: localhost:32000/docker-hello-world
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80